name: dimi
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python
  - pytorch
  - torchvision
  - cudatoolkit
  - jupyterlab
  - numpy
  - scikit-learn
  - matplotlib
  - ipython
  - jupyter
  - pandas
  - cython
  - pytest
  - tqdm
  - filelock
  - tensorboard
  - pip:
    - nbmerge
    - pytest-xdist