name: dimi
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python
  - pytorch
  - torchvision
  - cudatoolkit
  - jupyterlab
  - numpy
  - scikit-learn
  - matplotlib
  - ipython
  - jupyter
  - pandas
  - cython
  - pytest
  - tqdm
  - filelock
  - tensorboard
  - absl-py
  - scipy
  - gunicorn
  - pip
  - pip:
    - nbmerge
    - pytest-xdist
    - nlp
    - tensorflow
    - tensorflow-datasets
    - lime
    - rouge-score
    - sacrebleu
    - umap-learn
    - google-cloud-translate
    - rouge-score
    - annoy
    - transformers
    - datasets
